data_root: /home/yuliu/Dataset/Tool
use_aug: true

model: metaOptNet
model_args:
    encoder: resnet50
    encoder_args: {pretrained: false}
    head: ProtoNet
    normalize: false
#load_encoder: ./save/encoders/shape-moco-resnet12.pth
#load: ./save/meta_shape-bongard-6shot_meta-baseline-resnet12-seed123/epoch-last.pth
# train_from_ckpt: '/home/yuliu/Projects/Bongard-Tool/baselines/save/NS_metaOptNet_SC_ProtoNet/epoch-last.pth'

n_way: 2
n_shot: 6
n_query: 1
ep_per_batch: 16

max_epoch: 150
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: false
