data_root: /home/yuliu/Dataset/Tool
split_type: random
use_aug: true

model: wren
model_args:
    encoder: resnet50
    encoder_args: {pretrained: false}
    method: modified  # original
#load_encoder: ./materials/shape-moco-resnet12-epoch50.pth
#load: ./save/meta_shape-bongard-6shot_meta-baseline-resnet12-seed123/epoch-last.pth
train_from_ckpt: '/home/yuliu/Projects/Bongard-Tool/baselines/save/NS_wren_SC/epoch-last.pth'

n_way: 2
n_shot: 6
n_query: 1
ep_per_batch: 16

max_epoch: 150
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: false
