data_root: /code/Dataset
split_type: random
use_aug: true

model: maml
model_args:
    encoder: resnet50
    encoder_args: {pretrained: false}
    method: anil  # maml
    step_size: 0.4
    first_order: true
#load_encoder: ./materials/shape-moco-resnet12-epoch50.pth
#load: ./save/meta_shape-bongard-6shot_meta-baseline-resnet12-seed123/epoch-last.pth

n_way: 2
n_shot: 6
n_query: 1
train_batches: 1125
ep_per_batch: 16

max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: false
